config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  root 'static_pages#home'
  get 'static_pages/privacy'
  get 'static_pages/about'
  get "posts/tags"
  get "posts/categories"
  get "posts/autocomplete"
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{Rails.application.credentials.s3[:bucket_name]}/sitemap.xml.gz")
  resources :posts
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_taggable_on :tags, :categories
    validates_presence_of :title, :summary, :body
    def next
        self.class.where("id > ?", id).first
    end

    def prev
        self.class.where("id < ?", id).last
    end

    def related
        self.class.tagged_with(tag_list, any: true)
    end

    def latest(count = 5)
        self.class.last(count).reverse
    end

    def random(count = 4)
        self.class.find(self.class.pluck(:id).sample(count))
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_tags, only: %i[show tags index]
  before_action :set_categories, only: %i[show categories]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page])
    set_meta_tags title: "Posts",
      description: "記事一覧"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @tags = @tags.last(8)
    @categories = @categories.last(8)
    @q = Post.ransack(params[:q])
    set_meta_tags title: @post.title,
      description: @post.summary
  end

  def autocomplete
    q = Post.ransack(params[:q])
    posts = q.result(distinct: true).last(5)
    render json: posts
  end

  def tags
  end

  def categories
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.'}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_tags
      @tags = Post.tags_on(:tags)
    end

    def set_categories
      @categories = Post.tags_on(:categories)
    end
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :summary, :body, :tag_list, :category_list)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bottom-content.html.haml
%div.row.row-cols-1.row-cols-md-2.row-cols-lg-4.g-1
  - random_posts.each do |post|
    = render "posts/card/card-sm-y", post: post

app/views/posts/_form.html.haml
= javascript_include_tag 'load-mdfile', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'bootstrap-tagsinput', 'data-turbolinks-track': 'reload'

= form_with(model: post, local: true) do |form| 
  - if post.errors.any? 
    %div.alert.alert-danger{role: "alert"}
      %h2
        = pluralize(post.errors.count, "error") 
        prohibited this post from being saved:

      - post.errors.full_messages.each do |message| 
        %li= message

  %div.mb-3
    = form.label :title, class: "form-label"
    = form.text_field :title, class: "form-control", placeholder: "title"

  %div.mb-3
    = form.label :summary, class: "form-label"
    = form.text_field :summary, class: "form-control", placeholder: "summary"

  %div.mb-3
    = form.label :category_list, class: "form-label tagsinput"
    = form.text_field :category_list, class: "form-control",placeholder: "tag", data:{role: "tagsinput"}

  %div.mb-3
    = form.label :tag_list, class: "form-label tagsinput"
    = form.text_field :tag_list, class: "form-control", placeholder: "category", data:{role: "tagsinput"}, value: post.tag_list.join(", ")

  %div.mb-3
    = label :mdfile, :mdfile, class: "form-label"
    = file_field :mdfile, :mdfile, id: "mdFileField", class: "form-control"

  %div.mb-3
    = form.label :body, class: "form-label"
    = form.text_area :body, id: "mdTextArea",class: "form-control", placeholder: "body"

  %div.actions
    = form.button class:"btn btn-primary", type: "button", onclick: "submit();"

app/views/posts/_sidebar.html.haml
- posts = [["関連記事", post.related], ["最新記事", post.latest]]
- lists = [["カテゴリー", categories], ["タグ", tags]]

- posts.each do |title, posts|
  %h4.mt-5.mb-2.border-bottom= title
  - posts.each do |post|
    = render "posts/card/card-sm-x", post:post

-lists.each do |title, lists|
  %h4.mt-5.mb-2.border-bottom= title
  = render "sidebar_list", lists: lists

app/views/posts/_sidebar_list.haml
- list_group_item = "list-group-item list-group-item-action d-flex justify-content-between align-items-center hvr-backward"

%div.list-group.mb-5
  - lists.each do |list|
    = link_to posts_path(q: {tags_name_or_categories_name_cont: list.name}), class: list_group_item do
      = list.name
      %span.badge.bg-secondary= list.taggings_count
  = link_to "タグ一覧", posts_tags_path, class: list_group_item

app/views/posts/_tag_lists.html.haml
- tag_lists.each do |classname, name, tags|
  %i.fas{class: "fa-#{classname}"}
    = name
  - tags.each do |tag|
    = link_to tag, posts_path(q: {tags_name_or_categories_name_cont: tag.name}), class: "btn btn-secondary btn-sm"

app/views/posts/categories.html.haml
%h1 カテゴリ 
%div.list-group.mb-3
  - @categories.each do |category|
    = link_to category.name, posts_path(q: {title_or_tags_name_or_categories_name_cont: category.name}), class: "list-group-item list-group-item-action" 

app/views/posts/edit.html.haml
%h1 Editing Post

= render 'form', post: @post 

= link_to 'Show', @post 
|
= link_to 'Back', posts_path 

app/views/posts/index.html.haml
- if notice
  %div#notice.alert.alert-primary= notice 

%h1.mb-5= title "Posts"

= search_form_for @q, class: "d-flex mb-5" do |f|
  = f.search_field :title_or_tags_name_cont, id: "post-autocomplete", class: "form-control", placeholder: "Search", autocomplete: "off"
  = f.submit class: "btn btn-secondary ml-1" 

- @posts.each do |post|
  = render "posts/card/card", post: post

= paginate @posts

app/views/posts/new.html.haml
%h1 New Post

= render 'form', post: @post 

= link_to 'Back', posts_path 

app/views/posts/show.html.haml
- tag_lists = [["folder-open", "カテゴリー", @post.categories], ["tag", "タグ", @post.tags]]
- dates = [["upload", @post.created_at], ["redo-alt", @post.updated_at]]

- content_for :head do
  %script{ "data-ad-client" => "ca-pub-2292531594226333",  async: "", src: "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}

- if notice
  %div#notice.alert.alert-primary= notice

%div.row

  %div.col-12.col-md-8
    %div.d-flex.justify-content-around.align-items-center.w-100.mb-3.bg-secondary.text-white.post-show-img
      - @post.tags.each do |tag|
        %i.my-5.display-1{class: "devicon-#{tag}-plain"}

    %p
      %small.text-muted
        - dates.each do |classname, date|
          %i.fas.mr-3{class: "fa-#{classname}"}
            = date.strftime("%Y/%m/%d")
    %p
      %small.text-muted
        = render "tag_lists", tag_lists: tag_lists

    %div.bg-white.border.p-3
      - if admin_signed_in?    
        %div.btn-group.w-100
          = link_to 'Edit', edit_post_path(@post), class: "btn btn-success w-50"
          = link_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger w-50"


      %div.mt-3
        = markdown @post.body
        = social_share_button_tag(@post.title, allow_sites: %w(twitter facebook google_bookmark tumblr pinterest email reddit hacker_news))

    %div.container-fluid.mt-5
      %div.row
        -if prev_post = @post.prev
          %div.col-5.card.h-100.hvr-backward
            %div.row
              %div.col-0.col-lg-4.d-none.d-lg-flex.justify-content-center.align-items-center.bg-secondary.text-white
                %i.display-5{class: "devicon-#{prev_post.tags[0]}-plain"}
              %div.col-12.col-lg-8
                %div.card-body
                  %h6 
                    Prev : 
                    = link_to prev_post.title, prev_post, class: "text-body stretched-link" 
        -else
          %div.col-5

        -if next_post = @post.next
          %div.col-5.card.h-100.offset-2.hvr-forward
            %div.row
              %div.col-12.col-lg-8
                %div.card-body
                  %h6.card-title
                    Next : 
                    = link_to next_post.title, next_post, class: "text-body stretched-link"
              %div.col-0.col-lg-4.d-none.d-lg-flex.justify-content-center.align-items-center.bg-secondary.text-white
                %i.display-5{class: "devicon-#{next_post.tags[0]}-plain"}

    %div.mt-5
      = render "bottom-content", random_posts: @post.random

  %div.col-0.col-md-4.d-none.d-md-block
    = render "sidebar", post: @post, tags: @tags, categories: @categories

app/views/posts/tags.html.haml
%h1 Tags
%div.list-group.mb-3
  - @tags.each do |tag|
    = link_to tag.name, posts_path(q: {title_or_tags_name_or_categories_name_cont: tag.name}), class: "list-group-item list-group-item-action" 