config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  root 'static_pages#home'
  get 'static_pages/privacy'
  get 'static_pages/about'
  get "posts/tags"
  get "posts/categories"
  get "posts/autocomplete"
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{Rails.application.credentials.s3[:bucket_name]}/sitemap.xml.gz")
  resources :posts
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
- paths = {"お問い合わせ" => new_contact_path, "プライバシーポリシー" => static_pages_privacy_path}

%footer.my-5
  %ul.nav.justify-content-center
    - paths.each do |name, url|
      %li.nav-item
        = active_link_to name, url, active: :exact,class: "nav-link"

app/views/layouts/_header.html.haml
- paths = [["Home", root_path], ["About", static_pages_about_path], ["Posts",  posts_path], ["Contact", new_contact_path]]

%header.mb-5
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    %div.container-fluid

      = link_to "izszzz", root_path, class: "navbar-brand"

      %button.navbar-toggler{type: "button", "data-toggle" => "collapse", "data-target" => "#navbarToggler", "aria-controls" => "navbarToggler", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
        %span.navbar-toggler-icon

      %div#navbarToggler.collapse.navbar-collapse

        %ul.navbar-nav.mr-auto
          - paths.each do |name, url|
            %li.nav-item.hvr-underline-from-center= active_link_to name, url, active: :exact, class: "nav-link"
        
        = search_form_for @header_q, class: "d-flex", local: true do |f|
          = f.search_field :title_or_tags_name_cont, class: "form-control", placeholder: "Search", autocomplete: "off"
          %div.btn-group
            = f.submit class: "btn btn-secondary ml-1" 
            - if admin_signed_in?
              = link_to 'NewPost', new_post_path, class: "btn btn-primary", type: "button"
              = link_to 'SignOut', destroy_admin_session_path, method: :delete, class: "btn btn-danger", type: "button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tags 
    = csp_meta_tag 

    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %meta{name: "google-site-verification", content:"8hiZPxPAPxquo8xtvNL3dsRb-wu7MmyX65INIS3stHI"}
    - if Rails.env.production?
      %script{async: "", src: "https://www.googletagmanager.com/gtag/js?id=G-CZ1BWE20CB"}
      :javascript
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-CZ1BWE20CB');

    %link{rel: "stylesheet", href: "https://cdn.jsdelivr.net/gh/devicons/devicon@v2.9.0/devicon.min.css"}

    = display_meta_tags site: 'izszzz blog'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

- begin
  - if current_page?(root_path) || current_page?(posts_path) || current_page?(post_path)
    %script{ "data-ad-client" => "ca-pub-2292531594226333",  async: "", src: "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
- rescue

%body.bg-light
  = render "layouts/header"
  %div.container
    = yield 
  = render "layouts/footer"